{% set name = "heligeo" %}
{% set version = "1.1.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/heligeo-{{ version }}.tar.gz
  sha256: 308e9d31a8a385dc165bbe9926674866e99892c6bd645412ba193c04123416fe

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - dash ==2.0.0
    - dash-table
    - dash-bootstrap-components
    - dash-core-components
    - dash-html-components
    - numpy
    - pandas
    - plotly
    - python >={{ python_min }}
    - requests
    - shapely

test:
  imports:
    - heligeo
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/heligeo/
  summary: Python client for requests to heligeo API services
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - NandanPattanayak
