{% set name = "heligeo" %}
{% set version = "1.0.9" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/heligeo-{{ version }}.tar.gz
  sha256: 49a8785dbd68972d9465507211bf743d86c9bc0a103960b7eef67b62461403a4

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - dash
    - numpy
    - pandas
    - plotly
    - python >=3.6
    - requests
    - shapely

test:
  imports:
    - heligeo
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/heligeo/
  summary: Python client for requests to heligeo API services
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - NandanPattanayak
